server:
  port: 8083

spring:
  application:
    name: interface-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/interface_platform?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: platform
    password: platform123
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin123
  redis:
    host: localhost
    port: 6379
    database: 1
    timeout: 3000ms
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 3000ms
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # XML映射文件已迁移到MyBatis-Plus方式，不再需要mapper-locations配置
  # mapper-locations: classpath*:mapper/*.xml

# Feign配置
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000
        logger-level: basic
  hystrix:
    enabled: true

# 接口管理配置
interface:
  config:
    # 接口路径前缀
    path-prefix: /px-phzhb-external-share/dataproduct/
    # 默认超时时间（秒）
    default-timeout: 30
    # 默认限流配置（每分钟请求数）
    default-rate-limit: 1000
    # SQL查询超时时间（秒）
    sql-timeout: 60
    # 缓存过期时间（秒）
    cache-expire: 300
    # 批量操作最大数量
    batch-max-size: 100

# 日志配置
logging:
  level:
    com.powertrading.interfaces: DEBUG
    com.powertrading.interfaces.mapper: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/interface-service.log

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# OpenAPI文档配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  info:
    title: 接口管理服务API
    description: 电力交易中心接口服务平台 - 接口管理服务
    version: 1.0.0
    contact:
      name: PowerTrading Team