version: '3.8'

services:
  interface-platform-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: interface-platform-frontend
    ports:
      - "80:80"  # 映射到主机的80端口
      # - "8080:80"  # 如果80端口被占用，可以映射到8080
    environment:
      - NODE_ENV=production
    volumes:
      # 如果需要自定义nginx配置，可以挂载配置文件
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # 挂载日志目录（可选）
      - ./logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - interface-platform-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`your-domain.com`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

networks:
  interface-platform-network:
    driver: bridge

# 如果需要持久化日志
volumes:
  nginx-logs:
    driver: local