server:
  port: 8080

spring:
  application:
    name: gateway-service
  profiles:
    active: local
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        # 简单的测试路由
        - id: test-route
          uri: http://httpbin.org
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations: