server:
  port: 8080
  address: 127.0.0.1

spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  main:
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        # 用户服务路由
        - id: user-service
          uri: http://localhost:8086
          predicates:
            - Path=/user-service/api/v1/users/**
          filters:
            - StripPrefix=0
        # 系统管理路由
        - id: system-service
          uri: http://localhost:8087
          predicates:
            - Path=/system/**
          filters:
            - RewritePath=/system/(?<segment>.*), /user-service/system/$\{segment}
        # 系统统计API路由
        - id: system-stats
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/system/**
          filters:
            - RewritePath=/api/v1/system/(?<segment>.*), /user-service/api/v1/system/$\{segment}
        # 测试接口路由
        - id: test-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/test/**
          filters:
            - StripPrefix=0
        # MySQL表管理服务路由
        - id: mysql-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/mysql/**
          filters:
            - StripPrefix=0
        # 接口管理服务路由
        - id: interface-service-management
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/interfaces/**
          filters:
            - StripPrefix=0
        - id: interface-service-execution
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/execution/**
          filters:
            - StripPrefix=0
        - id: interface-service-status
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/status/**
          filters:
            - StripPrefix=0
        # 审批服务路由
        - id: approval-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/applications/**
          filters:
            - StripPrefix=0
        # 数据源服务路由
        - id: datasource-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/datasources/**
          filters:
            - StripPrefix=0
        # 认证服务路由
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=0
        # 通知服务路由
        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - StripPrefix=0
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: 
              - "*"
            allowed-methods: 
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
            allowed-headers: 
              - "*"
            exposed-headers:
              - "*"
            allow-credentials: false
            max-age: 3600
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 3000ms
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 3000ms

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.powertrading.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/gateway-service.log